import { TagCloud } from "../src/index.ts";

// ── 多模态标签云 ──
new TagCloud(document.getElementById("cloud")!, {
  tags: [
    {
      type: "html",
      html: '<div style="display:inline-flex;align-items:center;gap:10px;padding:6px 14px 6px 6px;border-radius:99px;background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.12);white-space:nowrap;cursor:pointer"><img src="https://xingwangzhe.fun/avatar.webp" width="32" height="32" style="border-radius:50%" alt="xingwangzhe" /><span style="font-weight:600;font-size:13px;color:#fff">xingwangzhe</span><span style="font-size:11px;color:rgba(255,255,255,0.5)">@GitHub</span></div>',
      onClick: () => window.open("https://github.com/xingwangzhe", "_blank"),
    },
    {
      type: "image",
      src: "https://xingwangzhe.fun/avatar.webp",
      width: 40,
      height: 40,
      onClick: () => window.open("https://github.com/xingwangzhe", "_blank"),
    },
    {
      type: "video",
      src: "https://clipqr.needhelp.icu/%E6%BC%94%E7%A4%BA%E8%A7%86%E9%A2%91.mp4",
      width: 120,
      height: 68,
    },
    "TypeScript",
    "Canvas",
    "3D",
    "WebGL",
    "WebGPU",
    "Rust",
    "Zig",
    "Bun",
    "Vite",
    "oxc",
    "ES6",
    "WASM",
    "Node.js",
    "Deno",
    "Astro",
    "Vue",
    "React",
    "Svelte",
    "Solid",
    "Qwik",
    "Docker",
    "Linux",
    "Nix",
    "Git",
    "GitHub",
    "Postgres",
    "SQLite",
    "Redis",
    "GraphQL",
    "CSS",
    "SVG",
    "WebSocket",
    "WebRTC",
    "oxlint",
    "oxfmt",
    "Biome",
    "Prettier",
    "Fibonacci",
    "Quaternion",
    "Arcball",
    "TagCloud",
    "Stalux",
    "xingwangzhe",
  ],
  onTagClick(item) {
    const urls: Record<string, string> = {
      TypeScript: "https://www.typescriptlang.org/",
      Rust: "https://www.rust-lang.org/",
      Zig: "https://ziglang.org/",
      Bun: "https://bun.sh/",
      Vite: "https://vite.dev/",
      Astro: "https://astro.build/",
      Vue: "https://vuejs.org/",
      React: "https://react.dev/",
      Svelte: "https://svelte.dev/",
      Solid: "https://www.solidjs.com/",
      Qwik: "https://qwik.dev/",
      Deno: "https://deno.com/",
      Docker: "https://www.docker.com/",
      Nix: "https://nixos.org/",
      Git: "https://git-scm.com/",
      GitHub: "https://github.com/",
      GraphQL: "https://graphql.org/",
      Postgres: "https://www.postgresql.org/",
      SQLite: "https://www.sqlite.org/",
      Redis: "https://redis.io/",
      WebGL: "https://www.khronos.org/webgl/",
      WebGPU: "https://www.w3.org/TR/webgpu/",
      WebRTC: "https://webrtc.org/",
      WebSocket: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
      WASM: "https://webassembly.org/",
      Canvas: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
      CSS: "https://developer.mozilla.org/en-US/docs/Web/CSS",
      SVG: "https://developer.mozilla.org/en-US/docs/Web/SVG",
      oxc: "https://oxc.rs/",
      oxlint: "https://oxc.rs/docs/guide/usage/linter.html",
      oxfmt: "https://oxc.rs/docs/guide/usage/formatter.html",
      Biome: "https://biomejs.dev/",
      Prettier: "https://prettier.io/",
      TagCloud: "https://github.com/xingwangzhe/tags-cloud",
      Stalux: "https://github.com/xingwangzhe/stalux",
      xingwangzhe: "https://xingwangzhe.fun",
    };
    const name = typeof item === "string" ? item : "";
    if (urls[name]) window.open(urls[name], "_blank");
  },
  radius: innerWidth < 768 ? 220 : 320,
  spinY: innerWidth < 768 ? 0.1 : 0.15,
  width: innerWidth < 768 ? innerWidth - 32 : 0,
  height: innerWidth < 768 ? 400 : 0,
});
